name: Generate Daily Blog

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup LLM
        run: |
          mkdir -p $GITHUB_WORKSPACE/models
          mkdir -p $GITHUB_WORKSPACE/llama
          curl -L "https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf" \
            -o $GITHUB_WORKSPACE/models/llama-2-7b-chat.gguf
          chmod 755 $GITHUB_WORKSPACE/models/llama-2-7b-chat.gguf
          curl -L https://github.com/ggml-org/llama.cpp/releases/download/b4778/llama-b4778-bin-ubuntu-x64.zip -o $GITHUB_WORKSPACE/llama/llama.zip
          unzip $GITHUB_WORKSPACE/llama/llama.zip -d $GITHUB_WORKSPACE/llama
          ls -lrt "$GITHUB_WORKSPACE/llama/build/bin/llama-cli" "$GITHUB_WORKSPACE/models/llama-2-7b-chat.gguf"
          sudo cp llama/build/bin/libllama.so /usr/local/lib
          sudo ldconfig
          chown -R $(id -u):$(id -g) .
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate blog
        run: npm run generate-blog
        env:
          USE_LOCAL_LLM: "true"
          LLAMA_BINARY_PATH: "/home/runner/work/blogs/blogs/llama/build/bin/llama-cli"
          LLAMA_MODEL_PATH: "/home/runner/work/blogs/blogs/models/llama-2-7b-chat.gguf"
          # Keep OpenAI as fallback
          VUE_APP_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add LLaMA-generated blog post" && git push)
